In [2]:
import numpy as np 
np= np.array([1, 2, 3, 4, 5])
print(np)

[1 2 3 4 5]


In [4]:
import numpy as np
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
#zeros
a=np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [7]:
#ones
a=np.ones(6)
print(a)

[1. 1. 1. 1. 1. 1.]


In [10]:
#empty
import numpy as np
b=np.empty(6)
print(b)

[1. 1. 1. 1. 1. 1.]


In [12]:
#arrange
a=np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [14]:
#printinf even numbers between 2 and 11
a=np.arange(2,11,2)
print(a)

[ 2  4  6  8 10]


In [16]:
x = np.ones(3, dtype=int)
print(x)
x

[1 1 1]


array([1, 1, 1])

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [20]:
#a[4] = 5
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)
a=np.delete(a, 4)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  6  7  8  9 10]


In [22]:
#sorting
a = np.array([56,33,11,22,99,55,66,5,4,1])
print(a)
a=np.sort(a)
print(a)

[56 33 11 22 99 55 66  5  4  1]
[ 1  4  5 11 22 33 55 56 66 99]


In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
a=arr.ndim
print(arr) 
print("dimensions = ", a)

[[1 2 3]
 [4 5 6]]
dimensions =  2


In [27]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b=arr.size
print(arr) 
print()
print("dimensions = ", a)
print("size = ", b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

dimensions =  2
size =  12


In [29]:
a = np.array(50)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 22, 33], [44, 55, 66]]])
print(a)
print("\ndimension= ", a.ndim)
print(b)
print("\ndimension= ", b.ndim)
print(c)
print("\ndimension= ", c.ndim)
print(d)
print("\ndimension= ", d.ndim)


50

dimension=  0
[1 2 3 4 5]

dimension=  1
[[1 2 3]
 [4 5 6]]

dimension=  2
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]

dimension=  3


In [31]:
#shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[11 ,22 ,33 ,44]])
print(arr.shape) 

(3, 4)


In [36]:
a = np.arange(6)
print(a)
b = a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
