In [4]:
import numpy as np
a=np.array(9)
print("A= ",a)

b=np.array([10,20,30])
print("\nB= ", b)

addition= np.add(a,b)
print("\nAfter Addition =", addition)

sub=np.subtract(b,a)
print("\nAfter Subtraction =",sub)

mul=np.multiply (a,b)
print("\nAfter Multiplcation =",mul)

div=np.divide (b,a)
print("\nAfter Division =",div)

div1=np.divide (a,4)
print("\nAfter Division =",div1)

A=  9

B=  [10 20 30]

After Addition = [19 29 39]

After Subtraction = [ 1 11 21]

After Multiplcation = [ 90 180 270]

After Division = [1.11111111 2.22222222 3.33333333]

After Division = 2.25


In [9]:
#reciprocal
a= np.array([1, 2.2, 4, 66])
print(a)
rec=np.reciprocal(a) 
print(rec)

[ 1.   2.2  4.  66. ]
[1.         0.45454545 0.25       0.01515152]


In [13]:
a=np.array([10,100,1000])
print(a)
pow=np.power(a,2)
print("a power 2 is = ", pow)

b=np.array([5,2,1])
print()
print(b)
pow1=np.power(a,b)
print("a ^ b = ", pow1)


[  10  100 1000]
a power 2 is =  [    100   10000 1000000]

[5 2 1]
a ^ b =  [100000  10000   1000]


In [17]:
a= np.array ([10,20,30])
b= np.array ([3,5,7])
print("values of A =", a)
print("values of B =", b)
x=np.mod(a,b)
y=np.remainder(a,b)

print("a MOD b=", x)
print("values of reminder=", y)



values of A = [10 20 30]
values of B = [3 5 7]
a MOD b= [1 0 2]
values of reminder= [1 0 2]


In [18]:
a=np.array([-5.5j, -4.4j, 0.5j, 11, 2+2j])
print(a)
print("\nreal=",np.real(a))
print("\nimaginary=",np.imag(a))
print("\nConjugate=", np.conj(a))

[-0.-5.5j -0.-4.4j  0.+0.5j 11.+0.j   2.+2.j ]

real= [-0. -0.  0. 11.  2.]

imaginary= [-5.5 -4.4  0.5  0.   2. ]

Conjugate= [-0.+5.5j -0.+4.4j  0.-0.5j 11.-0.j   2.-2.j ]


In [19]:
a=np.array ([2.0, 3.333, 7.35, 8.99, 5.3, 4])

print(a)
print("\nafter rounding up=", np.around(a))
print("\nafter rounding up to 1st decimal value =", np.around(a,decimals=1))

[2.    3.333 7.35  8.99  5.3   4.   ]

after rounding up= [2. 3. 7. 9. 5. 4.]

after rounding up to 1st decimal value = [2.  3.3 7.4 9.  5.3 4. ]


In [20]:
#floor and ceil
a=np.array ([1.0,-6.3,22.6,-0.45,25.5,30])
print(a)
print()
print(np.floor(a))
print(np.ceil(a))

[ 1.   -6.3  22.6  -0.45 25.5  30.  ]

[ 1. -7. 22. -1. 25. 30.]
[ 1. -6. 23. -0. 26. 30.]
